In [3]:
import torch
import math

In [4]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [6]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [7]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[5.2710e-08, 8.3092e+20, 1.9970e+20],
         [1.2812e-11, 1.0478e+21, 4.2533e-05]],

        [[4.1960e-08, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.1351e-43, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 3.9399e-34, 0.0000e+00]],

        [[4.3231e+17, 4.5646e-41, 3.9399e-34],
         [0.0000e+00, 9.1477e-41, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [8]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [9]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [10]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [12]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

#print(a * b)

In [13]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


In [14]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b)

c = a * torch.rand(3, 1)
print(c)

d = a * torch.rand(1, 2)
print(d)

tensor([[[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]]])
tensor([[[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]]])


In [15]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(4, 3)
c = a * torch.rand(2, 3)
d = a * torch.rand((0,))

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

More Math with Tensors

In [29]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

print('\nBroadcasted, element-wise equality comparion:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)
print(torch.eq(d, e))

print('\nReduction ops:')
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))

v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]])

print('\nVectors & Matrices:')
print(torch.cross(v2, v1))
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)
print(torch.svd(m3))

Common functions:
tensor([[0.6552, 0.5870, 0.3095, 0.6761],
        [0.9150, 0.9374, 0.0148, 0.4419]])
tensor([[1., 1., 1., -0.],
        [-0., -0., 1., 1.]])
tensor([[ 0.,  0.,  0., -1.],
        [-1., -1.,  0.,  0.]])
tensor([[ 0.5000,  0.5000,  0.3095, -0.5000],
        [-0.5000, -0.5000,  0.0148,  0.4419]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparion:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.6635, 0.1084],
        [0.1523, 0.8454]])
tensor([[1.9906, 0.3252],
        [0.4570, 2.5363]])
torch.return_types.svd(
U=tensor([[ 0.4496,  0.8932],
        [ 0.8932, -0.4496]]),
S=tensor([2.7413, 1.7876]),
V=tensor([[ 0.4754,  0.8798],
        [ 0.8798, -0.4754]]))


In [30]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [31]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1194, 0.7245],
        [0.6522, 0.1779]])

After adding:
tensor([[1.1194, 1.7245],
        [1.6522, 1.1779]])
tensor([[1.1194, 1.7245],
        [1.6522, 1.1779]])
tensor([[0.1194, 0.7245],
        [0.6522, 0.1779]])

After multiplying
tensor([[0.0143, 0.5249],
        [0.4253, 0.0317]])
tensor([[0.0143, 0.5249],
        [0.4253, 0.0317]])


In [33]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)

assert c is d
assert id(c) == old_id

torch.rand(2, 2, out=c)
print(c)
assert id(c) == old_id


tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3098, 0.2223],
        [0.2221, 0.1913]])
tensor([[0.7207, 0.3541],
        [0.9756, 0.1458]])


In [34]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [35]:
a = torch.ones(2, 2)
b = a.clone()
assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [36]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.2897, 0.1322],
        [0.0022, 0.8999]], requires_grad=True)
tensor([[0.2897, 0.1322],
        [0.0022, 0.8999]], grad_fn=<CloneBackward0>)
tensor([[0.2897, 0.1322],
        [0.0022, 0.8999]])
tensor([[0.2897, 0.1322],
        [0.0022, 0.8999]], requires_grad=True)


Moving to GPU

In [38]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

We have a GPU!


In [39]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


In [42]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.4629, 0.2537],
        [0.0404, 0.0187]], device='cuda:0')


In [43]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [46]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
z = x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Manipulating Tensor Shapes

In [49]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [50]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.8168]]]]])


In [52]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.2161, 0.5184, 0.8565, 0.7525, 0.7513, 0.6528, 0.1608, 0.0161, 0.0724,
         0.2802, 0.6153, 0.1011, 0.5788, 0.9595, 0.7025, 0.1325, 0.8977, 0.3612,
         0.6055, 0.2396]])
torch.Size([20])
tensor([0.2161, 0.5184, 0.8565, 0.7525, 0.7513, 0.6528, 0.1608, 0.0161, 0.0724,
        0.2802, 0.6153, 0.1011, 0.5788, 0.9595, 0.7025, 0.1325, 0.8977, 0.3612,
        0.6055, 0.2396])
torch.Size([2, 2])
torch.Size([2, 2])


In [55]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1)
print(c)

tensor([[[0.5070, 0.5070],
         [0.6969, 0.6969],
         [0.6666, 0.6666]],

        [[0.5070, 0.5070],
         [0.6969, 0.6969],
         [0.6666, 0.6666]],

        [[0.5070, 0.5070],
         [0.6969, 0.6969],
         [0.6666, 0.6666]],

        [[0.5070, 0.5070],
         [0.6969, 0.6969],
         [0.6666, 0.6666]]])


In [58]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)
c = b.unsqueeze(1)

print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.3818, 0.3818],
         [0.5320, 0.5320],
         [0.4613, 0.4613]],

        [[0.3818, 0.3818],
         [0.5320, 0.5320],
         [0.4613, 0.4613]],

        [[0.3818, 0.3818],
         [0.5320, 0.5320],
         [0.4613, 0.4613]],

        [[0.3818, 0.3818],
         [0.5320, 0.5320],
         [0.4613, 0.4613]]])


In [59]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [61]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [63]:
a = torch.rand(3, 4)
b = a.reshape(4, 3)
print(a)
print(b)

tensor([[1.0000e+07, 3.0681e-01, 8.9325e-01, 4.8762e-01],
        [2.2373e-01, 2.6106e-02, 1.2338e-01, 2.5807e-01],
        [3.2875e-01, 5.2229e-01, 2.2341e-01, 1.2776e-01]])
tensor([[1.0000e+07, 3.0681e-01, 8.9325e-01],
        [4.8762e-01, 2.2373e-01, 2.6106e-02],
        [1.2338e-01, 2.5807e-01, 3.2875e-01],
        [5.2229e-01, 2.2341e-01, 1.2776e-01]])


NumPy Brideg

In [64]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [65]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7859, 0.0785, 0.7513],
        [0.9056, 0.1668, 0.9224]])
[[0.78594255 0.07847565 0.7512636 ]
 [0.90563405 0.16681623 0.922356  ]]


In [66]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.78594255  0.07847565  0.7512636 ]
 [ 0.90563405 17.          0.922356  ]]
